### ISSUE TITLE
There might not be DOM content in the connectedCallback

### ISSUE THREAD

**Issue by Danny-Engelman** [andrico1234/autosize-textarea#1]
```
connectedCallback() {
    const textareaEl = this.querySelector('textarea');
```

There might not be a ``<textarea>``

See: https://dev.to/dannyengelman/web-component-developers-do-not-connect-with-the-connectedcallback-yet-4jo7

**Comment by andrico1234** [comment]
Thanks Danny, 

Great spot, 

fancy spinning up a PR that check to see if a textarea exists, and log an error if it doesn't?

Or do you think there's a more appropriate way of handling this error?

**Comment by Danny-Engelman** [comment]
See the long read I posted, a ``setTimeout`` will do

**Comment by andrico1234** [comment]
Thanks, resolved in v1.0.1

**Comment by Danny-Engelman** [comment]
I still see:

````
  connectedCallback() {
    const textareaEl = this.querySelector('textarea');
````

That is a red flag, the ``<textarea>``  you are after does not exist if the DOM isn't parsed yet
